name: my_maven
on: push

jobs: 
  build_project:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          architecture: x64
          cache: maven
      - name: Build with Maven
        run: mvn -B install --file pom.xml  
      - run: mkdir staging && cp /home/runner/work/MavenProject/MavenProject/webapp/target/*.war staging
      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging/webapp.war
  release_project:
    name: Release project
    runs-on: ubuntu-latest
    needs: build_project
    steps:
    - name: artifact download
    - uses: actions/download-artifact@v4
      with:
        name: Package
        path: $GITHUB_WORKSPACE
    - name: test artifact download
      run: ls -R               